server:
  port: 8083

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_allotment?createDatabaseIfNotExist=true
    username: root
    password: test
  jpa:
    hibernate.ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    format_sql: true
  application:
    name: PROJECT-SERVICE
  zipkin:
    base-url: http://localhost:9411/




